//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestorPortal
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

        protected global::System.Web.UI.WebControls.Panel pnlPurchaserNav;

        protected global::System.Web.UI.WebControls.Panel pnlAdminNav;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        protected global::System.Web.UI.WebControls.ImageButton ImageButton1;

        protected global::System.Web.UI.WebControls.ImageButton ImageButton2;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder scripts;
    }
}
