//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestorPortal
{
    public partial class AdminView
    {
        protected global::System.Web.UI.WebControls.Label lblStatus;

        protected global::System.Web.UI.WebControls.Label lblError;

        protected global::System.Web.UI.WebControls.DropDownList ddlPurchaser;

        protected global::System.Web.UI.WebControls.Button btnLoad;

        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        protected global::System.Web.UI.WebControls.TextBox txtEntity;

        protected global::System.Web.UI.WebControls.TextBox txtPurchaseAmount;

        protected global::System.Web.UI.WebControls.TextBox txtCashAmount;

        protected global::System.Web.UI.WebControls.TextBox txtAllocatedITC;

        protected global::System.Web.UI.WebControls.TextBox txtPendingITC;

        protected global::System.Web.UI.WebControls.TextBox txtWeightedITC;

        protected global::System.Web.UI.WebControls.TextBox txtProbability;

        protected global::System.Web.UI.WebControls.CheckBox chkPaymentPending;

        protected global::System.Web.UI.WebControls.CheckBox chkDocumentPending;

        protected global::System.Web.UI.WebControls.CheckBox chkCallScheduled;

        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
