//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestorPortal
{
    public partial class Projects
    {
        protected global::System.Web.UI.WebControls.Repeater rptProjects;

        protected global::System.Web.UI.WebControls.Label lblNoProjects;

        protected global::System.Web.UI.WebControls.ImageButton ImageButton1;

        protected global::System.Web.UI.WebControls.ImageButton ImageButton2;
    }
}
