//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestorPortal
{
    public partial class PurchaserDashboard
    {
        protected global::System.Web.UI.WebControls.Label name;

        protected global::System.Web.UI.WebControls.Label lblPortfolioSize;

        protected global::System.Web.UI.WebControls.Label lblAmountPaid;

        protected global::System.Web.UI.WebControls.Label lblAmountDue;

        protected global::System.Web.UI.WebControls.Label lblProjectCount;
    }
}
