//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestorPortal
{
    public partial class PurchaserPortal
    {
        protected global::System.Web.UI.WebControls.Panel pnlPaymentAlert;

        protected global::System.Web.UI.WebControls.Panel pnlDocumentAlert;

        protected global::System.Web.UI.WebControls.Label name;

        protected global::System.Web.UI.WebControls.Repeater rptProjects;
    }
}
