//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestorPortal
{
    public partial class PurchaseForm
    {
        protected global::System.Web.UI.WebControls.Panel pnlPaymentAlert;

        protected global::System.Web.UI.WebControls.Label Label1;

        protected global::System.Web.UI.HtmlControls.HtmlInputText projectName;

        protected global::System.Web.UI.HtmlControls.HtmlInputText pID;

        protected global::System.Web.UI.HtmlControls.HtmlInputText location;

        protected global::System.Web.UI.HtmlControls.HtmlInputText dType;

        protected global::System.Web.UI.HtmlControls.HtmlInputText bType;

        protected global::System.Web.UI.HtmlControls.HtmlInputText purchaseValue;

        protected global::System.Web.UI.HtmlControls.HtmlInputText itcValue;

        protected global::System.Web.UI.HtmlControls.HtmlInputText callDate;

        protected global::System.Web.UI.HtmlControls.HtmlInputText callTime;

        protected global::System.Web.UI.WebControls.Label lblResult;

        protected global::System.Web.UI.WebControls.Button submit;
    }
}
